rm(list = ls())

library(tidyverse)

load(file = "results/cwms/cwms.RData")

cwms %>%
  filter(Alliance != "Noise") %>%
  select(SIVIMID,
         Class,
         Alliance,
         floweringmean,
         floweringwidth,
         heightmax,
         geophyte, 
         therophyte,
         neophyte,
         Disturbance.Frequency,
         Disturbance.Severity,
         Grazing.Pressure,
         Mowing.Frequency,
         Soil.Disturbance,
         EIVE1.M,
         EIVE1.N,
         EIVE1.R,
         EIVE1.T,
         EIVE1.L) %>%
  gather(Trait, Value, floweringmean:EIVE1.L) %>%
  na.omit  %>%
  mutate(Trait = fct_relevel(Trait, 
                                "heightmax",
                                "floweringmean",
                                "floweringwidth",
                                "neophyte",
                                "geophyte",
                                "therophyte",
                                "EIVE1.T",
                                "EIVE1.M",
                                "EIVE1.L",
                                "EIVE1.N",
                                "EIVE1.R",
                                "Disturbance.Frequency",
                                "Disturbance.Severity",
                                "Soil.Disturbance",
                                "Mowing.Frequency",
                                "Grazing.Pressure")) %>%
  mutate(Trait = fct_recode(Trait, 
                            "Vegetation height (cm)" = "heightmax",
                            "Flowering peak (month)" = "floweringmean",
                            "Flowering length (months)" = "floweringwidth",
                            "Neophytes (% of total cover)" = "neophyte",
                            "Geophytes (% of total cover)" = "geophyte",
                            "Therophytes (% of total cover)" = "therophyte",
                            "Temperature (indicator)" = "EIVE1.T",
                            "Moisture (indicator)" = "EIVE1.M",
                            "Light (indicator)" = "EIVE1.L",
                            "Nutrients (indicator)" = "EIVE1.N",
                            "Soil reaction (indicator)" = "EIVE1.R",
                            "Disturbance frequency (indicator)" = "Disturbance.Frequency",
                            "Disturbance severity (indicator)" = "Disturbance.Severity",
                            "Soil disturbance (indicator)" = "Soil.Disturbance",
                            "Mowing frequency (indicator)" = "Mowing.Frequency",
                            "Grazing pressure (indicator)" = "Grazing.Pressure")) %>%
  mutate(Alliance = fct_relevel(Alliance, 
                               "Galio valantiae-Parietarion judaicae",
                               "Cymbalario-Asplenion",
                               "Polycarpion tetraphylli",
                               "Polygono-Coronopodion",
                               "Saginion procumbentis",
                               "Caucalidion lappulae",
                               "Scleranthion annui",
                               "Oxalidion europeae",
                               "Spergulo arvensis-Erodion cicutariae",
                               "Allion triquetri",
                               "Geranio pusilli-Anthriscion caucalidis",
                               "Chenopodion muralis",
                               "Echio-Galactition tomentosae",
                               "Linario polygalifoliae-Vulpion alopecuri",
                               "Sisymbrion officinalis",
                               "Convolvulo arvensis-Agropyrion repentis",
                               "Carduo carpetani-Cirsion odontolepidis",
                               "Silybo mariani-Urticion piluliferae", 
                               "Cirsion richterano-chodati",
                               "Dauco-Melilotion",
                               "Geo urbani-Alliarion officinalis",
                               "Arction lappae",
                               "Balloto-Conion maculati",
                               "Aegopodion podagrariae",
                               "Epilobion angustifolii",
                               "Cynancho-Convolvulion sepium",
                               "Senecionion fluviatilis",
                               "Bidention tripartitae",
                               "Paspalo-Agrostion semiverticillati")) %>%
  mutate(Class = fct_relevel(Class,
                             "Cymbalario-Parietarietea diffusae",
                             "Polygono-Poetea annuae",
                             "Papaveretea rhoeadis",
                             "Digitario sanguinalis-Eragrostietea minoris",
                             "Chenopodietea",
                             "Sisymbrietea",
                             "Artemisietea vulgaris",
                             "Epilobietea angustifolii",
                             "Bidentetea")) %>%
  mutate(Class = fct_recode(Class, 
                            "Artemisietea" = "Artemisietea vulgaris",
                            "Parietarietea" = "Cymbalario-Parietarietea diffusae",
                            "Digitario-Eragrostietea" = "Digitario sanguinalis-Eragrostietea minoris",
                            "Epilobietea" = "Epilobietea angustifolii",
                            "Papaveretea" = "Papaveretea rhoeadis",
                            "Polygono-Poetea" = "Polygono-Poetea annuae")) %>%
  mutate(group = as.numeric(Alliance)) %>%
  ggplot(aes(as.factor(group), Value, fill = Class)) +
  facet_wrap(~ Trait, scales = "free_y", ncol = 2) +
  geom_boxplot(outlier.size = 0.5,
               outlier.alpha = 0.6,
               lwd = 0.25) +
  scale_fill_manual(name = "Vegetation class",
                    values = c("grey40",
                               "cadetblue4",
                               "chocolate1", 
                               "chocolate4",
                               "firebrick3",
                               "khaki1",
                               "darkmagenta", 
                               "limegreen",
                               "goldenrod1")) +
  ggthemes::theme_tufte() +
  xlab("Alliance") + ylab("Value") +
  theme(text = element_text(family = "sans"),
        strip.background = element_blank(),
        legend.position = "bottom", 
        #legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.margin = margin(0, 0, 0, 0),
        legend.spacing.x = unit(0, "mm"),
        legend.spacing.y = unit(0, "mm"),
        legend.text = element_text(size = 9, face = "italic"), 
        panel.background = element_rect(color = "black", fill = NULL),
        strip.text = element_text(size = 12, hjust = 0, margin = margin(l = 0, b = 4)),
        #strip.text = element_blank(),
        plot.title = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6, color = "black"),
        axis.text.y = element_text(size = 8, color = "black"),
        plot.margin = unit(c(0.25,0.5,0,0.2), "cm")) -> Fig4

ggsave(Fig4, file = "results/figures/boxplots.png", bg = "white", 
       path = NULL, scale = 1, width = 179, height = 270, units = "mm", dpi = 600)

